/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const Genre = IDL.Variant({
  'pop' : IDL.Null,
  'bollywood' : IDL.Null,
  'folk' : IDL.Null,
  'ghazal' : IDL.Null,
  'devotional' : IDL.Null,
  'retro' : IDL.Null,
  'classical' : IDL.Null,
});
export const SongInput = IDL.Record({
  'coverImageUrl' : IDL.Text,
  'title' : IDL.Text,
  'duration' : IDL.Nat,
  'album' : IDL.Text,
  'genre' : Genre,
  'artist' : IDL.Text,
});
export const Song = IDL.Record({
  'id' : IDL.Nat,
  'coverImageUrl' : IDL.Text,
  'title' : IDL.Text,
  'duration' : IDL.Nat,
  'album' : IDL.Text,
  'genre' : Genre,
  'artist' : IDL.Text,
});

export const idlService = IDL.Service({
  'addSong' : IDL.Func([SongInput], [IDL.Nat], []),
  'getAllSongs' : IDL.Func([], [IDL.Vec(Song)], ['query']),
  'getSong' : IDL.Func([IDL.Nat], [Song], ['query']),
  'getSongsByGenre' : IDL.Func([Genre], [IDL.Vec(Song)], ['query']),
  'searchByArtist' : IDL.Func([IDL.Text], [IDL.Vec(Song)], ['query']),
  'searchByTitle' : IDL.Func([IDL.Text], [IDL.Vec(Song)], ['query']),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const Genre = IDL.Variant({
    'pop' : IDL.Null,
    'bollywood' : IDL.Null,
    'folk' : IDL.Null,
    'ghazal' : IDL.Null,
    'devotional' : IDL.Null,
    'retro' : IDL.Null,
    'classical' : IDL.Null,
  });
  const SongInput = IDL.Record({
    'coverImageUrl' : IDL.Text,
    'title' : IDL.Text,
    'duration' : IDL.Nat,
    'album' : IDL.Text,
    'genre' : Genre,
    'artist' : IDL.Text,
  });
  const Song = IDL.Record({
    'id' : IDL.Nat,
    'coverImageUrl' : IDL.Text,
    'title' : IDL.Text,
    'duration' : IDL.Nat,
    'album' : IDL.Text,
    'genre' : Genre,
    'artist' : IDL.Text,
  });
  
  return IDL.Service({
    'addSong' : IDL.Func([SongInput], [IDL.Nat], []),
    'getAllSongs' : IDL.Func([], [IDL.Vec(Song)], ['query']),
    'getSong' : IDL.Func([IDL.Nat], [Song], ['query']),
    'getSongsByGenre' : IDL.Func([Genre], [IDL.Vec(Song)], ['query']),
    'searchByArtist' : IDL.Func([IDL.Text], [IDL.Vec(Song)], ['query']),
    'searchByTitle' : IDL.Func([IDL.Text], [IDL.Vec(Song)], ['query']),
  });
};

export const init = ({ IDL }) => { return []; };