/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Actor, HttpAgent, type HttpAgentOptions, type ActorConfig, type Agent, type ActorSubclass } from "@icp-sdk/core/agent";
import type { Principal } from "@icp-sdk/core/principal";
import { idlFactory, type _SERVICE } from "./declarations/backend.did";
export interface Some<T> {
    __kind__: "Some";
    value: T;
}
export interface None {
    __kind__: "None";
}
export type Option<T> = Some<T> | None;
function some<T>(value: T): Some<T> {
    return {
        __kind__: "Some",
        value: value
    };
}
function none(): None {
    return {
        __kind__: "None"
    };
}
function isNone<T>(option: Option<T>): option is None {
    return option.__kind__ === "None";
}
function isSome<T>(option: Option<T>): option is Some<T> {
    return option.__kind__ === "Some";
}
function unwrap<T>(option: Option<T>): T {
    if (isNone(option)) {
        throw new Error("unwrap: none");
    }
    return option.value;
}
function candid_some<T>(value: T): [T] {
    return [
        value
    ];
}
function candid_none<T>(): [] {
    return [];
}
function record_opt_to_undefined<T>(arg: T | null): T | undefined {
    return arg == null ? undefined : arg;
}
export class ExternalBlob {
    _blob?: Uint8Array<ArrayBuffer> | null;
    directURL: string;
    onProgress?: (percentage: number) => void = undefined;
    private constructor(directURL: string, blob: Uint8Array<ArrayBuffer> | null){
        if (blob) {
            this._blob = blob;
        }
        this.directURL = directURL;
    }
    static fromURL(url: string): ExternalBlob {
        return new ExternalBlob(url, null);
    }
    static fromBytes(blob: Uint8Array<ArrayBuffer>): ExternalBlob {
        const url = URL.createObjectURL(new Blob([
            new Uint8Array(blob)
        ], {
            type: 'application/octet-stream'
        }));
        return new ExternalBlob(url, blob);
    }
    public async getBytes(): Promise<Uint8Array<ArrayBuffer>> {
        if (this._blob) {
            return this._blob;
        }
        const response = await fetch(this.directURL);
        const blob = await response.blob();
        this._blob = new Uint8Array(await blob.arrayBuffer());
        return this._blob;
    }
    public getDirectURL(): string {
        return this.directURL;
    }
    public withUploadProgress(onProgress: (percentage: number) => void): ExternalBlob {
        this.onProgress = onProgress;
        return this;
    }
}
export interface SongInput {
    coverImageUrl: string;
    title: string;
    duration: bigint;
    album: string;
    genre: Genre;
    artist: string;
}
export interface Song {
    id: bigint;
    coverImageUrl: string;
    title: string;
    duration: bigint;
    album: string;
    genre: Genre;
    artist: string;
}
export enum Genre {
    pop = "pop",
    bollywood = "bollywood",
    folk = "folk",
    ghazal = "ghazal",
    devotional = "devotional",
    retro = "retro",
    classical = "classical"
}
export interface backendInterface {
    addSong(songInput: SongInput): Promise<bigint>;
    getAllSongs(): Promise<Array<Song>>;
    getSong(id: bigint): Promise<Song>;
    getSongsByGenre(genre: Genre): Promise<Array<Song>>;
    searchByArtist(searchText: string): Promise<Array<Song>>;
    searchByTitle(searchText: string): Promise<Array<Song>>;
}
import type { Genre as _Genre, Song as _Song, SongInput as _SongInput } from "./declarations/backend.did.d.ts";
export class Backend implements backendInterface {
    constructor(private actor: ActorSubclass<_SERVICE>, private _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, private _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, private processError?: (error: unknown) => never){}
    async addSong(arg0: SongInput): Promise<bigint> {
        if (this.processError) {
            try {
                const result = await this.actor.addSong(to_candid_SongInput_n1(this._uploadFile, this._downloadFile, arg0));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addSong(to_candid_SongInput_n1(this._uploadFile, this._downloadFile, arg0));
            return result;
        }
    }
    async getAllSongs(): Promise<Array<Song>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllSongs();
                return from_candid_vec_n5(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllSongs();
            return from_candid_vec_n5(this._uploadFile, this._downloadFile, result);
        }
    }
    async getSong(arg0: bigint): Promise<Song> {
        if (this.processError) {
            try {
                const result = await this.actor.getSong(arg0);
                return from_candid_Song_n6(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getSong(arg0);
            return from_candid_Song_n6(this._uploadFile, this._downloadFile, result);
        }
    }
    async getSongsByGenre(arg0: Genre): Promise<Array<Song>> {
        if (this.processError) {
            try {
                const result = await this.actor.getSongsByGenre(to_candid_Genre_n3(this._uploadFile, this._downloadFile, arg0));
                return from_candid_vec_n5(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getSongsByGenre(to_candid_Genre_n3(this._uploadFile, this._downloadFile, arg0));
            return from_candid_vec_n5(this._uploadFile, this._downloadFile, result);
        }
    }
    async searchByArtist(arg0: string): Promise<Array<Song>> {
        if (this.processError) {
            try {
                const result = await this.actor.searchByArtist(arg0);
                return from_candid_vec_n5(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.searchByArtist(arg0);
            return from_candid_vec_n5(this._uploadFile, this._downloadFile, result);
        }
    }
    async searchByTitle(arg0: string): Promise<Array<Song>> {
        if (this.processError) {
            try {
                const result = await this.actor.searchByTitle(arg0);
                return from_candid_vec_n5(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.searchByTitle(arg0);
            return from_candid_vec_n5(this._uploadFile, this._downloadFile, result);
        }
    }
}
function from_candid_Genre_n8(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Genre): Genre {
    return from_candid_variant_n9(_uploadFile, _downloadFile, value);
}
function from_candid_Song_n6(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Song): Song {
    return from_candid_record_n7(_uploadFile, _downloadFile, value);
}
function from_candid_record_n7(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: bigint;
    coverImageUrl: string;
    title: string;
    duration: bigint;
    album: string;
    genre: _Genre;
    artist: string;
}): {
    id: bigint;
    coverImageUrl: string;
    title: string;
    duration: bigint;
    album: string;
    genre: Genre;
    artist: string;
} {
    return {
        id: value.id,
        coverImageUrl: value.coverImageUrl,
        title: value.title,
        duration: value.duration,
        album: value.album,
        genre: from_candid_Genre_n8(_uploadFile, _downloadFile, value.genre),
        artist: value.artist
    };
}
function from_candid_variant_n9(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    pop: null;
} | {
    bollywood: null;
} | {
    folk: null;
} | {
    ghazal: null;
} | {
    devotional: null;
} | {
    retro: null;
} | {
    classical: null;
}): Genre {
    return "pop" in value ? Genre.pop : "bollywood" in value ? Genre.bollywood : "folk" in value ? Genre.folk : "ghazal" in value ? Genre.ghazal : "devotional" in value ? Genre.devotional : "retro" in value ? Genre.retro : "classical" in value ? Genre.classical : value;
}
function from_candid_vec_n5(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_Song>): Array<Song> {
    return value.map((x)=>from_candid_Song_n6(_uploadFile, _downloadFile, x));
}
function to_candid_Genre_n3(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Genre): _Genre {
    return to_candid_variant_n4(_uploadFile, _downloadFile, value);
}
function to_candid_SongInput_n1(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: SongInput): _SongInput {
    return to_candid_record_n2(_uploadFile, _downloadFile, value);
}
function to_candid_record_n2(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    coverImageUrl: string;
    title: string;
    duration: bigint;
    album: string;
    genre: Genre;
    artist: string;
}): {
    coverImageUrl: string;
    title: string;
    duration: bigint;
    album: string;
    genre: _Genre;
    artist: string;
} {
    return {
        coverImageUrl: value.coverImageUrl,
        title: value.title,
        duration: value.duration,
        album: value.album,
        genre: to_candid_Genre_n3(_uploadFile, _downloadFile, value.genre),
        artist: value.artist
    };
}
function to_candid_variant_n4(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Genre): {
    pop: null;
} | {
    bollywood: null;
} | {
    folk: null;
} | {
    ghazal: null;
} | {
    devotional: null;
} | {
    retro: null;
} | {
    classical: null;
} {
    return value == Genre.pop ? {
        pop: null
    } : value == Genre.bollywood ? {
        bollywood: null
    } : value == Genre.folk ? {
        folk: null
    } : value == Genre.ghazal ? {
        ghazal: null
    } : value == Genre.devotional ? {
        devotional: null
    } : value == Genre.retro ? {
        retro: null
    } : value == Genre.classical ? {
        classical: null
    } : value;
}
export interface CreateActorOptions {
    agent?: Agent;
    agentOptions?: HttpAgentOptions;
    actorOptions?: ActorConfig;
    processError?: (error: unknown) => never;
}
export function createActor(canisterId: string, _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, options: CreateActorOptions = {}): Backend {
    const agent = options.agent || HttpAgent.createSync({
        ...options.agentOptions
    });
    if (options.agent && options.agentOptions) {
        console.warn("Detected both agent and agentOptions passed to createActor. Ignoring agentOptions and proceeding with the provided agent.");
    }
    const actor = Actor.createActor<_SERVICE>(idlFactory, {
        agent,
        canisterId: canisterId,
        ...options.actorOptions
    });
    return new Backend(actor, _uploadFile, _downloadFile, options.processError);
}
